
spring:
  profiles:
      active: dev
  jpa:
   database: MYSQL

server:
  port: 8085

mybatis:
  typeAliasesPackage: com.aim.questionnaire.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true

pagehelper:
  helperDalect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: conut=countSql

commonDS:
  initialSize: 2
  minIdle: 2
  maxActive: 5
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 60000

  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 5
  filters: stat,wall,slf4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  useGlobalDataSourceStat: true
  loginUsername: star
  loginPassword: Star1234
  resetEnable: false
  rootPath: /druid/*

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://39.99.231.41/questionnaire?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: lying
    password: lying
    driver-class-name: com.mysql.cj.jdbc.Driver


